# Generated by Django 4.1.5 on 2023-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_of_sleep', models.IntegerField()),
                ('breakfast', models.CharField(max_length=200)),
                ('sleep_quality', models.IntegerField()),
                ('feeling', models.IntegerField()),
                ('sweet', models.CharField(max_length=200)),
                ('memo', models.CharField(max_length=200)),
            ],
        ),
    ]
