# Generated by Django 4.1.5 on 2023-03-22 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='breakfast',
            field=models.CharField(max_length=5, verbose_name='朝ごはん'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='date',
            field=models.DateField(unique=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='feeling',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='今日の気分'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='hours_of_sleep',
            field=models.IntegerField(verbose_name='睡眠時間'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='memo',
            field=models.CharField(blank=True, max_length=200, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='sleep_quality',
            field=models.IntegerField(verbose_name='睡眠の質'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='sweet',
            field=models.CharField(blank=True, max_length=200, verbose_name='おやつ'),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='tags',
            field=models.ManyToManyField(blank=True, to='breakfast.tag', verbose_name='タグ'),
        ),
    ]
