# Generated by Django 4.1.5 on 2023-03-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0002_tag_alter_breakfast_breakfast_alter_breakfast_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='breakfast',
            field=models.CharField(max_length=30, verbose_name='朝ごはん'),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='category',
            field=models.ManyToManyField(blank=True, to='breakfast.category', verbose_name='カテゴリ'),
        ),
    ]
