# Generated by Django 4.1.5 on 2023-03-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0003_category_alter_breakfast_breakfast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='category',
        ),
        migrations.AddField(
            model_name='breakfast',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='breakfast.category', verbose_name='カテゴリ'),
        ),
    ]
