# Generated by Django 4.1.5 on 2023-04-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0004_remove_breakfast_category_breakfast_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakfast',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='breakfast.category', verbose_name='カテゴリ'),
        ),
    ]
