# Generated by Django 4.1.5 on 2023-04-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0005_alter_breakfast_options_alter_breakfast_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='画像'),
        ),
    ]
