# Generated by Django 4.1.5 on 2023-04-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0006_breakfast_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='画像'),
        ),
    ]
