# Generated by Django 4.1.5 on 2023-04-04 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0007_alter_breakfast_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='daytime_sleepiness',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='昼間の眠気'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breakfast',
            name='impressions_of_the_day',
            field=models.TextField(blank=True, verbose_name='今日の感想'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='sleep_quality',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='睡眠の質'),
        ),
    ]
